# Generated by Selenium IDE
from operator import index

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import requests

class RoboPje():
    def index():
        error = 0
        driver = webdriver.Firefox()
        driver.get("https://esaj.tjsp.jus.br/sajcas/login")
        driver.set_window_size(1050, 748)
        driver.find_element(By.ID, "usernameForm").click()
        driver.find_element(By.ID, "usernameForm").send_keys("967.933.923-87")
        driver.find_element(By.ID, "passwordForm").click()
        driver.find_element(By.ID, "passwordForm").send_keys("wolf3126294")
        driver.find_element(By.ID, "pbEntrar").click()
        driver.find_element(By.CSS_SELECTOR,
                            ".esajTabelaServico:nth-child(5) .esajCelulaDescricaoServicos > a").click()
        driver.find_element(By.CSS_SELECTOR,
                            ".esajTabelaServico:nth-child(3) .esajCelulaDescricaoServicos > a").click()
        getProcessos = requests.get('https://github.com/timeline.json')
        if(getProcessos.status_code == 200):
            processosCapturados = getProcessos.json()
            driver.find_element(By.ID, "numeroDigitoAnoUnificado").click()
            driver.find_element(By.ID, "pbEnviar").click()
        else:
            print('Erro ao capturar os processos do servidor')
            print('Tentando novamente')
            error =+ 1
            if(error > 3):
                time.sleep(60)
                index()
    index()