# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSadasd():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sadasd(self):
    self.driver.get("https://pje1g.trf3.jus.br/pje/login.seam")
    self.driver.set_window_size(550, 693)
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("wolf3126294")
    self.driver.find_element(By.ID, "btnEntrar").click()
    element = self.driver.find_element(By.ID, "btnEntrar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "btnEntrar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".botao-menu > span").click()
    self.driver.find_element(By.LINK_TEXT, "Processo").click()
    self.driver.find_element(By.LINK_TEXT, "Pesquisar").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .nivel-aberto li:nth-child(1) > a").click()
  
